# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-16 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='head_img',
            field=models.ImageField(blank=True, null=True, upload_to='upload', verbose_name='用户图片'),
        ),
    ]
